name: Reuse workflows Publish Docker image

on:
  workflow_dispatch: # Manual trigger from GitHub Actions UI



jobs:
  call-workflow:
    permissions:
      contents: read
      packages: write # Required for push to GitHub Registry (GHCR)
      attestations: write # Required for provenance
      id-token: write # Required for modern attestations/provenances (OIDC)
      artifact-metadata: write # Required to create the artifact storage record.
    # owner/repository/.github/workflows/workflows.yml@main' or '././.github/workflows/workflows.yml' for local workflows
    uses: ./.github/workflows/docker.yml
    with:
      USE_GITHUB_REGISTRY: true



