name: Reuse workflows Publish Docker image

on:
  workflow_dispatch: # Manual trigger from GitHub Actions UI

jobs:
  call-workflow:
    # owner/repository/.github/workflows/workflows.yml@main' or '././.github/workflows/workflows.yml' for local workflows
    uses: ./.github/workflows/docker.yml
    with:
      USE_GITHUB_REGISTRY: true



