name: concurrency

on:
  workflow_dispatch: # Manual trigger from GitHub Actions UI
  push:

concurrency: # Prevent multiple runs from executing simultaneously
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-slim
    steps:
      - name: concurrency group
        run: echo ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
      - name: sleep
        run: sleep 1
