name: job outputs
on:
  workflow_dispatch: # Manual trigger from GitHub Actions UI
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: Compute image name
        id: img
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
      - name: outputs
        run: echo "${{ toJSON(steps.img.outputs) }}"
      - name: outputs img
        run: echo ${{ steps.img.outputs.IMAGE }}

      - name: Login to GitHub Registry
        id: login
        if: vars.USE_GITHUB_REGISTRY == 'true'
        uses: docker/login-action@v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: img
        run: echo "${{ toJSON(steps.login.outputs) }}"

      - name: Compute image name
        id: img2
        run: | 
          echo IMAGES= >> $GITHUB_OUTPUT
          if [ "${{ vars.USE_GITHUB_REGISTRY }}" = "true" ]; then
            echo "ghcr.io/${{ github.repository }}" >> $GITHUB_OUTPUT
          fi
          images=$(
            for img in ${{ vars.DOCKER_IMAGES }}; do
              [[ "$img" == *.*/* ]] || img="mydomain.com/$img"
              echo "$img"
            done
          ) >> $GITHUB_OUTPUT
      - name: outputs img
        run: echo ${{ steps.img2.outputs.IMAGES }}

        
