name: pr-trigger

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-slim
    steps:
      - run: echo test


